Dev/jgough/v2 schema
datatrails/datatrails-simplehash-python pull request #12
Opened 2023-03-29 14:20 UTC by honourfish

2023-03-29 15:11 UTC, eccles requested changes
So v1.py has been modified to remove 'public' where appropriate and v2.py does not bother (i.e. its the same as the original v1.py). Is that correct and expected.

Also are there unittests and has the README.md been modified to mention v2 as well as v1?

2023-03-31 08:29 UTC, honourfish commented
> So v1.py has been modified to remove 'public' where appropriate and v2.py does not bother (i.e. its the same as the original v1.py). Is that correct and expected.
> 
> Also are there unittests and has the README.md been modified to mention v2 as well as v1?

Yes! thats exactly it, have updated the unittests, will also update the readme!

2023-03-31 08:38 UTC, honourfish commented
updated readme

2023-03-31 09:49 UTC, eccles requested changes
LGTM

When will the user use one of the 4 options presented in the README. maybe a bit of text at the top of READMEto point the user to teh correct option?

2023-03-31 09:49 UTC, eccles commented on README.rst
> +    CLIENT_ID=$(cat credentials/client_id)
is this needed?

2023-03-31 09:56 UTC, honourfish commented on README.rst
> +    CLIENT_ID=$(cat credentials/client_id)
not for public no

2023-03-31 10:06 UTC, eccles approved these changes

2023-03-31 10:06 UTC, merged